FROM node:22-slim AS builder

WORKDIR /app
COPY ./frontend .

ARG VITE_API_HOST
ENV VITE_API_HOST=$VITE_API_HOST

RUN npm install && npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]