FROM node:22-slim

WORKDIR /app
COPY ./frontend .
RUN npm install --omit=dev && npm install -g @nestjs/cli

ENTRYPOINT ["npx", "prisma", "migrate", "deploy"]
CMD ["nest", "start", "--env-file", ".env"]