FROM node:22-slim AS builder

WORKDIR /app
COPY ./frontend .
RUN npm install && npm run build
RUN ls -la /app/dist

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]