FROM node:22-slim

WORKDIR /app
COPY . .
RUN apt-get update -y && apt-get install -y openssl && npm install --omit=dev && npm install -g @nestjs/cli

CMD ["sh", "-c", "npx prisma migrate deploy && nest start"]