# A CHANGER LORSQU'ON VA FUSIONER A LA BRANCHE MAIN POUR GERER LES DOSSIERS FRONT/BACK
name: Build, Test, and Deploy Docker to Render (test version) !ONLY FOR BACK CURRENTLY!

on:
  push:
    branches: [guilherme]

jobs:
  back_build:
    name: Build Backend project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run build
        working-directory: backend
        run: ./node_modules/.bin/nest build

  back_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: back_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run tests
        working-directory: backend
        run: npm run test

  back_deploy:
    name: Build and Deploy backend to Render
    runs-on: ubuntu-latest
    needs: back_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t efreisocialnetwork/socialnetworkbackend:latest -f dockerfile.backend .

      - name: Push Docker image
        run: docker push efreisocialnetwork/socialnetworkbackend:latest

      - name: Trigger Deploy on Render
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST "https://api.render.com/deploy/srv-d0vdb295pdvs738coprg?key=${{secrets.RENDER_API_KEY}}")

          if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
            echo "✅ Deploy triggered successfully (HTTP $response)"
          else
            echo "❌ Render deploy failed with HTTP status $response"
            cat response.txt
            exit 1
          fi

#   front_build:
#     name: Build Frontend project
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
  
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 22

#       - name: Install dependencies
#         working-directory: frontend
#         run: npm install

#       - name: Run build
#         working-directory: frontend
#         run: npm run build

#   front_test:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest
#     needs: back_build

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 22

#       - name: Install dependencies
#         working-directory: backend
#         run: npm install

#       - name: Run tests
#         working-directory: backend
#         run: npm run test

  front_deploy:
    name: Build and Deploy frontend to Render
    runs-on: ubuntu-latest
    needs: back_deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --build-arg VITE_API_HOST=${{secrets.VITE_API_HOST}} -t efreisocialnetwork/socialnetworkfrontend:latest -f dockerfile.frontend .

      - name: Push Docker image
        run: docker push efreisocialnetwork/socialnetworkfrontend:latest

      - name: Trigger Deploy on Render
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST "https://api.render.com/deploy/srv-d17vd9odl3ps7398tl0g?key=${{secrets.RENDER_FRONT_API_KEY}}")

          if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
            echo "✅ Deploy triggered successfully (HTTP $response)"
          else
            echo "❌ Render deploy failed with HTTP status $response"
            cat response.txt
            exit 1
          fi
