name: Build, Test, and Deploy Docker to Render (test version)

on:
  push:
    branches: [guilherme]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy_back:
    name: Build and Deploy backend to Render
    runs-on: ubuntu-latest
    needs: test # <-- Run only if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t efreisocialnetwork/socialnetworkbackend:latest -f dockerfile.backend .

      - name: Push Docker image
        run: docker push efreisocialnetwork/socialnetworkbackend:latest

      - name: Trigger Deploy on Render
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST "https://api.render.com/deploy/srv-d0vdb295pdvs738coprg?key=${{secrets.RENDER_API_KEY}}")

          if [ "$response" -ge 200 ] && [ "$status_code" -lt 300 ]; then
            echo "✅ Deploy triggered successfully (HTTP $response)"
          else
            echo "❌ Render deploy failed with HTTP status $response"
            cat response.txt
            exit 1
          fi
